### ISSUE TITLE
Error with registry_name

### ISSUE THREAD

**Issue by frarin** [AgicCloud/Demo.Aks.Performance#17]
![image](https://user-images.githubusercontent.com/98345119/169474960-5728fa21-8571-4944-8179-5cfae2c1dec8.png)

![image](https://user-images.githubusercontent.com/98345119/169475063-d38a8238-e999-46c7-8075-76038199af44.png)

![image](https://user-images.githubusercontent.com/98345119/169475133-0e328eb5-4e9c-4476-9f9f-fd8f50014c2c.png)

**Comment by frarin** [comment]
Now I have the same error I had yesterday: 
![image](https://user-images.githubusercontent.com/98345119/169476623-8073bd25-c79e-4095-bbb9-849e9af9cef3.png)

**Comment by mosca97** [comment]
@frarin the error was in the helm chart name, it does not accept special characters like "_"
we have now introduced a transformation to remove these characters.
