### ISSUE TITLE
AKS autoscale

### ISSUE THREAD

**Issue by filippo-cala** [AgicCloud/Demo.Aks.Performance#20]
Ciao,
da un test che ho effettuato mi sembra che l'AKS che viene instanziato non sia impostato come autoscale true, la soluzione dovrebbe dimostrare proprio l'elasticità sia dei pod che dell'infrastruttura.
Potete verificare?

Grazie mille,

FIlippo

**Comment by macel94** [comment]
@filippo-cala 
Ciao Filippo

grazie per il chiarimento, a breve sarà approvata la PR qui sopra dove abbiamo implementato le modifiche richieste per rendere evidente l'elasticità sia orizzontale che verticale della soluzione proposta in questo repository.

Restiamo a disposizione
