### ISSUE TITLE
AZ Login Failed

### ISSUE THREAD

**Issue by filippo-cala** [AgicCloud/Demo.Aks.Performance#22]
If I follow this step on my laptop through Azure CLI plugin:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/85103736/170234256-f96771af-e18c-4aec-b271-2437ca382952.png">

The Az Login error is shown during the pipeline execution:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/85103736/170234675-091b8e20-9525-4cce-a122-acaf2b44204a.png">

If I run the same command and generate the json token from Azure Bash all works fine.

**Comment by macel94** [comment]
Hi @filippo-cala 

we saw that you succeded in deploying the solution: 
https://github.com/filippo-cala/Demo.Aks.Performance/actions/runs/2383469315
I guess there was an error during the copy paste of your secret?

We will go ahead and close this issue.
