### ISSUE TITLE
No roles for Azure Load Testing

### ISSUE THREAD

**Issue by filippo-cala** [AgicCloud/Demo.Aks.Performance#24]
If I open the Azure Load Testing page I cannot see nothing and this message is present:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/85103736/170235711-8c13b1f9-f31b-4787-8950-739261b525b5.png">

**Comment by macel94** [comment]
Hello

we reproduced the problem and will now integrate the docs, thank you for opening this issue.
If you see an error like this one:
![image](https://user-images.githubusercontent.com/85103736/170235711-8c13b1f9-f31b-4787-8950-739261b525b5.png)
You can solve it by going in the Access Control blade of your Azure Load Testing detail and assigning yourself one of these roles:
![image](https://user-images.githubusercontent.com/8000532/170243532-97bc1dba-aec8-40b0-8cf3-6472124cc51e.png)

Please confirm us you managed to do it, thank you.

**Comment by macel94** [comment]
@filippo-cala
